spring:
  application:
    name: infra-api-gateway
  config:
    import: "configserver:"
  cloud:
    config:
      uri: http://localhost:8888

profiles:
  active: dev   # o prod, o los que correspondan